services:
  app:
    image: todo-app-frontend-dev
    build:
      context: .
      dockerfile: ./todo-frontend/dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 3001:3000
    container_name: todo-app-frontend-dev
  debug-helper:
    image: busybox
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8000:80
    container_name: reverse_proxy
    depends_on:
      - app